In [11]:
from datetime import datetime

now = datetime.now()
print("현재 시간 : ", now.date())


현재 시간 :  2023-03-03 15:59:49.264272


In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

1.13.1
False


In [2]:
#기본 연산 단위
x = torch.tensor([1,2])
print(x)
x = torch.rand(2,3)
print(x)
x = torch.zeros(2,3,dtype = torch.long)
print(x)
x = torch.ones(2,3,dtype = torch.long)
print(x)
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([1, 2])
tensor([[0.3193, 0.6005, 0.4830],
        [0.7246, 0.4974, 0.6459]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[-0.0231,  1.0742, -0.8501],
        [-1.0221,  0.2391, -1.6052]])


In [3]:
#torch 연산
y = torch.ones(2,3)
y.add(x)
y.add_(x) # add_ : y = y.add(x)로 대체한다.
y

tensor([[ 0.9769,  2.0742,  0.1499],
        [-0.0221,  1.2391, -0.6052]])

In [4]:
y[1,2]#인덱싱

tensor(-0.6052)

In [5]:
x = torch.rand(8,8)
print(x.view(64))#view : 리스트처럼 변환
print(x.view(-1, 16))# print(x.view(4,16))
print(x.view(-1,4,2))

tensor([0.9784, 0.0495, 0.1820, 0.8444, 0.8173, 0.3654, 0.1802, 0.1195, 0.7152,
        0.4156, 0.4489, 0.8234, 0.4437, 0.6311, 0.8303, 0.7355, 0.3254, 0.8429,
        0.2684, 0.3006, 0.6270, 0.7991, 0.3113, 0.4940, 0.7805, 0.5640, 0.4319,
        0.5255, 0.0519, 0.9494, 0.5135, 0.5339, 0.8242, 0.8730, 0.2129, 0.9065,
        0.9342, 0.3878, 0.4950, 0.7324, 0.1599, 0.6573, 0.2499, 0.7579, 0.6039,
        0.6597, 0.2637, 0.9509, 0.9530, 0.5399, 0.1865, 0.9204, 0.9100, 0.2500,
        0.2247, 0.9629, 0.1206, 0.2796, 0.3885, 0.2127, 0.6636, 0.4561, 0.1468,
        0.9534])
tensor([[0.9784, 0.0495, 0.1820, 0.8444, 0.8173, 0.3654, 0.1802, 0.1195, 0.7152,
         0.4156, 0.4489, 0.8234, 0.4437, 0.6311, 0.8303, 0.7355],
        [0.3254, 0.8429, 0.2684, 0.3006, 0.6270, 0.7991, 0.3113, 0.4940, 0.7805,
         0.5640, 0.4319, 0.5255, 0.0519, 0.9494, 0.5135, 0.5339],
        [0.8242, 0.8730, 0.2129, 0.9065, 0.9342, 0.3878, 0.4950, 0.7324, 0.1599,
         0.6573, 0.2499, 0.7579, 0.6039, 0.6597,

In [6]:
x.view(64)#.item()

tensor([0.9784, 0.0495, 0.1820, 0.8444, 0.8173, 0.3654, 0.1802, 0.1195, 0.7152,
        0.4156, 0.4489, 0.8234, 0.4437, 0.6311, 0.8303, 0.7355, 0.3254, 0.8429,
        0.2684, 0.3006, 0.6270, 0.7991, 0.3113, 0.4940, 0.7805, 0.5640, 0.4319,
        0.5255, 0.0519, 0.9494, 0.5135, 0.5339, 0.8242, 0.8730, 0.2129, 0.9065,
        0.9342, 0.3878, 0.4950, 0.7324, 0.1599, 0.6573, 0.2499, 0.7579, 0.6039,
        0.6597, 0.2637, 0.9509, 0.9530, 0.5399, 0.1865, 0.9204, 0.9100, 0.2500,
        0.2247, 0.9629, 0.1206, 0.2796, 0.3885, 0.2127, 0.6636, 0.4561, 0.1468,
        0.9534])

In [7]:
x = x.view(64)
torch.sum(x).item() # tensor의 sum > item은 스칼라값만 추출하기

34.73768997192383